<?php

$_TASK = array(
	"qfsv0" => "createBags",
	"zsnj1" => "addBagItems",
	"bbbx2" => "createSyncBags",
	"ipr3" => "isSync",
	"uyeq4" => "submitCartAbandonEmail",
	"wiaw5" => "validateDiscount",
	"fjea6" => "subscribe",
	"etnu7" => "submitSignup",
	"yepx8" => "validateAccessCode",
	"xbfy9" => "getStateTax",
	"dgula" => "signDelivery",
	"wubqb" => "submitLogin",
	"sgfnc" => "skipSingleOrder",
	"pfjud" => "donateSingleOrder",
	"pnvte" => "removeSkippedOrder",
	"fhndf" => "getProducts",
	"lcaig" => "stopSubscription",
	"effhh" => "updateBilling",
	"mztii" => "toggleArchiveUser",
	"tvykj" => "issueRefund",
	"acxpk" => "resetCustomerPassword",
	"ifjxl" => "changeCustomerSite",
	"tdqzm" => "submitSinglePayment",
	"ldcxn" => "togglePublishDiscount",
	"fcejo" => "changeItemStatus",
	"hjrup" => "changeSupplierStatus",
	"ijbaq" => "assignSite",
	"dzldr" => "hideDeliverySite",
	"ahtjs" => "toggleEnabledDeliverySite",
	"nbfgt" => "changeSiteDeliveryDay",
	"fwequ" => "removeDriver",
	"zgmev" => "resendEmail",
	"iqoqw" => "addSubscription",
	"zejhx" => "skipOrders",
	"nliry" => "changeSubscription",
	"jtukz" => "editProfile",
	"antnA" => "newPassword",
	"oztuB" => "addDiscount",
	"vyjuC" => "addProduct",
	"dvymD" => "addItem",
	"lmbkE" => "addSupplier",
	"qlrdF" => "addCategory",
	"wzufG" => "addDeliverySite",
	"roprH" => "editSite",
	"aiepI" => "addDriverAccount",
	"hyibJ" => "submitForgotPassword"
);

$_POST['task'] = $_TASK[$_POST['vqvyl_']];

?>